static_app_name     = "kiwauno-dev-static-app"
global_region       = "northeurope"
frontend_region     = "westeurope"
resource_group_name = "rg-kiwauno-dev"
sku_tier            = "Free"
admin_password = "20kiwauno-ctrancoso26"
