global_region          = "northeurope"
resource_group_name    = "rg-kiwauno-dev"
sku_tier               = "Free"
admin_password         = "20kiwauno-ctrancoso26"
grafana_admin_password = "20grafana-ctrancoso26"
zone                   = "1"
image_ref              = "kiwaunodevacr.azurecr.io/backend:dev"
frontend_image_ref     = "kiwaunodevacr.azurecr.io/frontend:dev"