name: Deploy App to AKS

on:
  workflow_dispatch:
    inputs:
      env:
        description: "Environment"
        required: true
        type: choice
        options:
          - 'dev'
          - 'prod'
      image_tag:
        description: "Image tag"
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ inputs.env }}

    env:
      ACR_LOGIN_SERVER: ${{ inputs.env == 'prod' && vars.ACR_LOGIN_SERVER_PROD || vars.ACR_LOGIN_SERVER_DEV }}
      RESOURCE_GROUP: ${{ inputs.env == 'prod' && vars.RESOURCE_GROUP_PROD || vars.RESOURCE_GROUP_DEV }}
      AKS_CLUSTER_NAME: ${{ inputs.env == 'prod' && vars.AKS_CLUSTER_NAME_PROD || vars.AKS_CLUSTER_NAME_DEV }}

    steps:
      - uses: actions/checkout@v4

      - name: Log in to Azure
        uses: azure/login@v3
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Get AKS credentials
        run: |
          az aks get-credentials \
            --resource-group "$RESOURCE_GROUP" \
            --name "$AKS_CLUSTER_NAME" \

      - name: Deploy backend
        run: |
          kubectl set image deployment/backend \
            backend=$ACR_LOGIN_SERVER/backend:${{ inputs.image_tag }} \
            --namespace default

      - name: Deploy frontend
        run: |
          kubectl set image deployment/frontend \
            frontend=$ACR_LOGIN_SERVER/frontend:${{ inputs.image_tag }} \
            --namespace default

      - name: Wait for backend rollout
        run: kubectl rollout status deployment/backend --namespace default --timeout=180s

      - name: Wait for frontend rollout
        run: kubectl rollout status deployment/frontend --namespace default --timeout=180s